FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

ENV SC_VERSION 3.10.2
ENV SC_MAJORVERSION 3.10
ENV SC_PLUGIN_VERSION 3.10.0

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -yq --no-install-recommends \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    git \
    jackd \
    libasound2-dev \
    libavahi-client-dev \
    libcwiid-dev \
    libfftw3-dev \
    libicu-dev \
    libjack-dev \
    libjack0 \
    libreadline6-dev \
    libsndfile1-dev \
    libudev-dev \
    libxt-dev \
    pkg-config \
    unzip \
    wget \
    xvfb \
  \
  && rm -rf /var/lib/apt/lists/*
  
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FABAEF95 && \
    add-apt-repository -y ppa:supercollider/ppa && \
    add-apt-repository -y multiverse && \
    apt-get update && \
    apt-get install -y icecast2 darkice libasound2 libasound2-plugins alsa-utils alsa-oss jack-tools supercollider xvfb curl && \
    apt-get clean

RUN curl -o forego.tgz https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-amd64.tgz && \
    tar xvf forego.tgz && \
    rm forego.tgz && \
    mv forego /usr/bin/forego && \
    chmod +x /usr/bin/forego

RUN apt-get update 
RUN apt-get install -y lame
RUN apt-get install -y curl
RUN apt-get install -y vorbis-tools
RUN apt-get install -y nano

COPY asoundrc /root/.asoundrc

COPY icecast.xml /etc/icecast2/icecast.xml
COPY darkice.cfg /etc/darkice.cfg

COPY startup.scd /root/.config/SuperCollider/startup.scd
COPY radio.sc /radio.sc

COPY Procfile Procfile
RUN mv /etc/security/limits.d/audio.conf.disabled /etc/security/limits.d/audio.conf && \
    usermod -a -G audio root

EXPOSE 8000
EXPOSE 57120

RUN mkdir /usr/share/SuperCollider/downloaded-quarks
RUN mkdir /usr/share/SuperCollider/synthdefs

COPY /app/SuperCollider/downloaded-quarks /usr/share/SuperCollider/downloaded-quarks
COPY /app/SuperCollider/synthdefs /usr/share/SuperCollider/synthdefs
COPY . .



CMD ["forego", "start"]


#USER sclang



#RUN mkdir /home/sclang/.config
#RUN mkdir /home/sclang/.config/SuperCollider

#ENTRYPOINT ["sclang"]
