# base image
FROM node:8.12.0

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies

COPY . ./

EXPOSE 8080

# start app
# ENTRYPOINT ["node"]