version: "3"

services:
  fourteen_api_streaming:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: bash -c "sleep 10; python3 manage.py runserver"
    environment:
      - DEV_POSTGRES_URL=postgres:5432
      - FLASK_ENV=development
    ports:
      - "5001:5001"
      - "5555:5555"
    depends_on:
      - postgres_fourteen
    restart: on-failure
    volumes:
      - ../app:/home/app
      - ./out_streams:/home/app/SuperCollider
    networks:
      default:

  postgres_fourteen:
    container_name: postgres_fourteen
    restart: always
    image: mdillon/postgis:11
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      default:

  sc_streaming:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-sc
    command: "forego start"
    ports:
      - "57120:57120/udp"
      - "8000:8000"
      - "5556:5555"
    restart: unless-stopped
    volumes:
      - ../app:/home/sclang/.local/share
      - ./out_streams:/app/SuperCollider
    networks:
      default:
        ipv4_address: 10.5.0.11

volumes:
  pg_data:
  out_streams:

networks:
  default:
    external:
      name: local_network_dev
