flask_server:
  host: 0.0.0.0
  passthrough_errors: false
  port: 5001
  processes: 1
  ssl_crt: null
  ssl_key: null
  threaded: true
  use_debugger: true
  use_reloader: null
gunicorn_server:
  gunicorn_host: 0.0.0.0
  gunicorn_port: 5000
  gunicorn_workers: 4
postgres:
  DEBUG: true
  SECRET_KEY: "test-secret-key"
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  db_host: "postgres_fourteen"
  db_name: "fourteen_backend"
  db_password: "fourteen"
  db_psql_base_uri: "postgresql+psycopg2"
  db_sql_base_uri: "mysql+pymysql"
  db_username: "fourteen"
postgres_test:
  DEBUG: true
  SECRET_KEY: "test-secret-key"
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  db_host: "postgres_fourteen_test"
  db_name: "fourteen_backend_test"
  db_password: "fourteen"
  db_psql_base_uri: "postgresql+psycopg2"
  db_sql_base_uri: "mysql+pymysql"
  db_username: "fourteen"
API_HOST: /api
